<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NORF524" failures="0" tests="2" name="runner.TestngRunner" time="8.082" errors="1" timestamp="2024-03-02T11:59:31 IST" skipped="0">
  <testcase classname="runner.TestngRunner" name="runScenario" time="3.321">
    <error message="Incorrect Error Message" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Incorrect Error Message
at dev.failsafe.internal.util.Assert.isTrue(Assert.java:29)
at AutomationProject.StepDefinitions.StepDefinitionImp.verify_the_errormessage(StepDefinitionImp.java:75)
at âœ½.verify the 'Sorry, this user has been locked out.'(file:///C:/Users/ADMIN/eclipse-workspace4/JavaSeleniumFramework/src/test/java/features/ErrorValidation.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestngRunner" name="runScenario" time="4.761"/>
  <system-out/>
</testsuite> <!-- runner.TestngRunner -->
